export const content = {
  uz: {
    nav: ['Xizmatlar', 'Ishlarimiz', 'Jarayon', 'Agentlik', 'Aloqa'],
    cta: 'Konsultatsiya olish',
    heroEyebrow: 'Natijaga asoslangan marketing agentligi',
    heroTitle: ['Marketingni', 'daromadga', 'aylantiramiz'],
    heroText:
      'Strategiya, kontent, reklama va analitikani yagona tizimga birlashtirib, biznesingizga real mijozlar oqimini quramiz.',
    heroPrimary: 'Bepul konsultatsiya olish',
    heroSecondary: 'Ishlarimizni ko‘rish',
    trust: 'Strategiya. Kontent. O‘sish.',
    trustSub: 'Bitta tizim. Aniq natija.',
    stats: [
      { value: '140', suffix: '%', label: 'Murojaatlar o‘sishi' },
      { value: '38', suffix: 'x', label: 'Reklama rentabelligi', decimal: true },
      { value: '27', suffix: '%', prefix: '−', label: 'Xarajatni kamaytirish' },
      { value: '30', suffix: ' kun', label: 'Marketing tizimi' },
    ],
    marquee: ['Strategiya', 'Performance', 'Kontent', 'Brending', 'Web development', 'Sotuv tizimi'],
    servicesKicker: 'Xizmatlarimiz',
    servicesTitle: ['Biz nima', 'qilamiz?'],
    servicesDesc:
      'Biznesingiz o‘sishi uchun kerakli marketing xizmatlarini bitta strategiyada va bitta jamoada jamlaymiz.',
    services: [
      {
        title: 'Performance marketing',
        text: 'Meta, Google, TikTok va boshqa platformalarda maqsadli kampaniya, kreativ va optimallashtirish.',
        icon: 'chart',
      },
      {
        title: 'Sotuv tizimini qurish',
        text: 'CRM, lead management, sotuv voronkasi va operatsion jarayonlarni bir tizimga solamiz.',
        icon: 'target',
      },
      {
        title: 'Kompleks marketing',
        text: 'Brending, kontent, reklama va sotuvni yagona growth strategiyada birlashtiramiz.',
        icon: 'layers',
      },
      {
        title: 'Web va mobil mahsulotlar',
        text: 'Konversiyaga yo‘naltirilgan sayt, landing page va raqamli mahsulotlar yaratamiz.',
        icon: 'code',
      },
    ],
    worksKicker: 'Tanlangan loyihalar',
    worksTitle: ['Strategiya ko‘rinadi.', 'Natija seziladi.'],
    worksDesc:
      'Har bir loyiha uchun vizual, kontent va reklama yechimlari biznes maqsadiga mos ravishda ishlab chiqiladi.',
    projects: ['Azizon', 'Chorvachi', 'Rail City', 'Visola', 'Tosh Stone', 'Minor Group', 'Tabriz', 'PureMilky', 'Marg‘ilon Plaza', 'Osh Palove'],
    processKicker: 'Ishlash jarayoni',
    processTitle: ['Tasodif emas.', 'Tizimli natija.'],
    processDesc: 'Har bir bosqich o‘lchanadi. Har bir qaror biznes maqsadiga bog‘lanadi.',
    processCta: 'Loyihani muhokama qilish',
    process: [
      ['Audit va diagnostika', 'Biznes, bozor, raqobatchilar va joriy marketing holatini chuqur tahlil qilamiz.'],
      ['Strategiya va taklif', 'Pozitsiya, kontent yo‘nalishlari, reklama gipotezalari va KPI xaritasini tuzamiz.'],
      ['Ishga tushirish', 'Kontent, reklama va leadlarni qayta ishlash jarayonini yagona ritmda ishga tushiramiz.'],
      ['Tahlil va optimallashtirish', 'Raqamlarni kuzatamiz, ishlaydigan yechimlarni kuchaytiramiz va o‘sishni tezlashtiramiz.'],
    ],
    aboutKicker: 'Revenue yondashuvi',
    aboutTitle: ['Kontent emas,', 'natija', 'yaratamiz.'],
    aboutText:
      'Revenue biznesingizning ichki jarayonlarini tushunib, strategiya, kontent, reklama va analitikani bitta boshqariladigan tizimga birlashtiradi.',
    quote: '“Marketing — tasodifiy postlar emas. Bu biznes o‘sishini boshqaradigan tizim.”',
    aboutPoints: ['Biznes maqsadidan boshlaymiz', 'Har bir ishni o‘lchaymiz', 'Ishlaydigan yechimni kuchaytiramiz'],
    contactKicker: 'Bepul konsultatsiya',
    contactTitle: 'Biznesingiz uchun yutuqli yurishni boshlaymiz.',
    contactDesc:
      'Qisqa ma’lumot qoldiring. So‘rov matni nusxalanadi va Revenue Telegram sahifasi ochiladi.',
    form: {
      name: 'Ismingiz',
      phone: 'Telefon raqamingiz',
      business: 'Biznes yo‘nalishi',
      message: 'Maqsadingiz',
      send: 'So‘rov yuborish',
      status: 'Ma’lumot nusxalandi. Telegram oynasi ochilmoqda…',
    },
    footer: 'Marketingni daromadga aylantiramiz.',
    rights: 'Barcha huquqlar himoyalangan.',
    demo: '*Ko‘rsatkichlar demo. Saytni ishga tushirishdan oldin real case raqamlari bilan almashtiring.',
  },
  ru: {
    nav: ['Услуги', 'Проекты', 'Процесс', 'Агентство', 'Контакты'],
    cta: 'Получить консультацию',
    heroEyebrow: 'Маркетинговое агентство, ориентированное на результат',
    heroTitle: ['Преобразуем', 'маркетинг', 'в прибыль'],
    heroText:
      'Объединяем стратегию, контент, рекламу и аналитику в единую систему, которая приводит реальных клиентов.',
    heroPrimary: 'Бесплатная консультация',
    heroSecondary: 'Посмотреть проекты',
    trust: 'Стратегия. Контент. Рост.',
    trustSub: 'Одна система. Понятный результат.',
    stats: [
      { value: '140', suffix: '%', label: 'Рост обращений' },
      { value: '38', suffix: 'x', label: 'Рентабельность рекламы', decimal: true },
      { value: '27', suffix: '%', prefix: '−', label: 'Снижение расходов' },
      { value: '30', suffix: ' дней', label: 'Маркетинговая система' },
    ],
    marquee: ['Стратегия', 'Performance', 'Контент', 'Брендинг', 'Web development', 'Система продаж'],
    servicesKicker: 'Наши услуги',
    servicesTitle: ['Что мы', 'делаем?'],
    servicesDesc:
      'Собираем все необходимые маркетинговые услуги в одну стратегию и одну команду для роста бизнеса.',
    services: [
      {
        title: 'Performance marketing',
        text: 'Кампании в Meta, Google, TikTok и других каналах: аудитория, креатив и оптимизация.',
        icon: 'chart',
      },
      {
        title: 'Создание системы продаж',
        text: 'Объединяем CRM, управление лидами, воронку и операционные процессы.',
        icon: 'target',
      },
      {
        title: 'Комплексный маркетинг',
        text: 'Соединяем брендинг, контент, рекламу и продажи в единую growth-стратегию.',
        icon: 'layers',
      },
      {
        title: 'Web и мобильные продукты',
        text: 'Создаём конверсионные сайты, landing page и цифровые продукты.',
        icon: 'code',
      },
    ],
    worksKicker: 'Избранные проекты',
    worksTitle: ['Стратегию видно.', 'Результат ощущается.'],
    worksDesc:
      'Для каждого проекта визуал, контент и реклама разрабатываются под конкретную бизнес-цель.',
    projects: ['Azizon', 'Chorvachi', 'Rail City', 'Visola', 'Tosh Stone', 'Minor Group', 'Tabriz', 'PureMilky', 'Marg‘ilon Plaza', 'Osh Palove'],
    processKicker: 'Процесс работы',
    processTitle: ['Не случайность.', 'Системный результат.'],
    processDesc: 'Каждый этап измеряется. Каждое решение связано с бизнес-целью.',
    processCta: 'Обсудить проект',
    process: [
      ['Аудит и диагностика', 'Глубоко анализируем бизнес, рынок, конкурентов и текущее состояние маркетинга.'],
      ['Стратегия и предложение', 'Формируем позиционирование, контент-направления, гипотезы и карту KPI.'],
      ['Запуск', 'Запускаем контент, рекламу и обработку лидов в едином рабочем ритме.'],
      ['Аналитика и оптимизация', 'Следим за цифрами, усиливаем рабочие решения и ускоряем рост.'],
    ],
    aboutKicker: 'Подход Revenue',
    aboutTitle: ['Не контент,', 'результат', 'создаём.'],
    aboutText:
      'Revenue погружается во внутренние процессы бизнеса и объединяет стратегию, контент, рекламу и аналитику в управляемую систему.',
    quote: '«Маркетинг — это не случайные посты. Это система, которая управляет ростом бизнеса».',
    aboutPoints: ['Начинаем с бизнес-цели', 'Измеряем каждое действие', 'Усиливаем рабочие решения'],
    contactKicker: 'Бесплатная консультация',
    contactTitle: 'Начнём выигрышный ход для вашего бизнеса.',
    contactDesc:
      'Оставьте краткую информацию. Текст заявки скопируется и откроется Telegram Revenue.',
    form: {
      name: 'Ваше имя',
      phone: 'Ваш номер телефона',
      business: 'Направление бизнеса',
      message: 'Ваша цель',
      send: 'Отправить заявку',
      status: 'Информация скопирована. Открываем Telegram…',
    },
    footer: 'Преобразуем маркетинг в прибыль.',
    rights: 'Все права защищены.',
    demo: '*Показатели демонстрационные. Перед запуском замените их реальными данными кейсов.',
  },
};
